name: app_reproductor_multiplataforma
description: "A new Flutter project."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # ─── Lógica y networking ──────────────────────────────────────────────────────
  http: ^1.2.1
  shared_preferences: ^2.2.3
  device_info_plus: ^10.0.0
  package_info_plus: ^8.3.0
  crypto: ^3.0.3
  jwt_decoder: ^2.0.1
  network_info_plus: ^5.0.3

  # ─── Reproductores ────────────────────────────────────────────────────────────
  video_player: ^2.10.0   # ⬅️  versión reciente con fixes de progreso
  chewie:       ^1.12.1   # ⬅️  compatible con video_player ≥2.9

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true        # para .arb/locales
